name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0-100.2.beta

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.9.0
  provider: ^6.1.5+1
  intl: ^0.20.2
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.5.3
  mockito: ^5.5.1
  google_sign_in: ^6.1.4
  sign_in_button: ^4.0.1
  flutter_signin_button: ^2.1.1
  file_picker: ^10.3.3
  csv: ^6.0.0
  image_picker: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.8.0

flutter:
  uses-material-design: true
