// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVpc6aAWFZJnOBPU9gR42m-8cMRbDQhgQ',
    appId: '1:999658223369:web:e787538af864f5046745d8',
    messagingSenderId: '999658223369',
    projectId: 'tiendaapp-9dde8',
    authDomain: 'tiendaapp-9dde8.firebaseapp.com',
    storageBucket: 'tiendaapp-9dde8.firebasestorage.app',
    measurementId: 'G-WWH0M9CMDD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmnK2bqSflKkpVd4eLjPI_VY8T3zuI6Jk',
    appId: '1:999658223369:android:b23c95ba8c09f4bf6745d8',
    messagingSenderId: '999658223369',
    projectId: 'tiendaapp-9dde8',
    storageBucket: 'tiendaapp-9dde8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQquCcBhOW7PTrZQZrlfU5PdnH0kCaTao',
    appId: '1:999658223369:ios:b1c244f047a989a56745d8',
    messagingSenderId: '999658223369',
    projectId: 'tiendaapp-9dde8',
    storageBucket: 'tiendaapp-9dde8.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQquCcBhOW7PTrZQZrlfU5PdnH0kCaTao',
    appId: '1:999658223369:ios:b1c244f047a989a56745d8',
    messagingSenderId: '999658223369',
    projectId: 'tiendaapp-9dde8',
    storageBucket: 'tiendaapp-9dde8.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVpc6aAWFZJnOBPU9gR42m-8cMRbDQhgQ',
    appId: '1:999658223369:web:2a330c8b3880e1b76745d8',
    messagingSenderId: '999658223369',
    projectId: 'tiendaapp-9dde8',
    authDomain: 'tiendaapp-9dde8.firebaseapp.com',
    storageBucket: 'tiendaapp-9dde8.firebasestorage.app',
    measurementId: 'G-Z6F9K74CVS',
  );
}
